{% set version = "2.4.1" %}

package:
  name: cryptography-vectors
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cryptography_vectors/cryptography_vectors-{{ version }}.tar.gz
  sha256: 829d43e8066056de8ea7b8ad311db79e47d8d658e23d5f5fc4b0245a1b3baa74

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography
  license: Apache 2.0 or BSD 3-Clause
  #license_file: ??? TWO LICENSE FILES ???
  summary: Test vectors for the cryptography package.
  dev_url: https://github.com/pyca/cryptography/tree/master/vectors
  doc_url: https://cryptography.io

extra:
  recipe-maintainers:
    - jakirkham
