{% set name = "cryptography-vectors" %}
{% set version = "42.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptography_vectors-{{ version }}.tar.gz
  sha256: adcdccf5d9ee661a9602ad21d2525f678ba07a6e768ce79835994e208bab0e16

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - flit-core
    - setuptools
    - wheel

  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: Apache
  license_file: LICENSE
  summary: Test vectors for cryptography.
  description: |
    This package contains test vectors for the cryptography package.
  dev_url: https://github.com/pyca/cryptography/tree/main/vectors
  doc_url: https://cryptography.io/

extra:
  recipe-maintainers:
    - jakirkham
