{% set name = "cryptography-vectors" %}
{% set version = "43.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptography_vectors-{{ version }}.tar.gz
  sha256: ff6a885265f484e8907277614b73e9c774b01658623ad763dde2858188e486b4

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
    - pip
    - flit-core >=3.2,<4
  run:
    - python
  run_constrained:
    - bcrypt >=3.1.5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  summary: Test vectors for cryptography.
  description: |
    This package contains test vectors for the cryptography package.
  dev_url: https://github.com/pyca/cryptography/tree/main/vectors
  doc_url: https://cryptography.io/

extra:
  recipe-maintainers:
    - jakirkham
