{% set name = "cryptography-vectors" %}
{% set version = "44.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptography_vectors-{{ version }}.tar.gz
  sha256: 5a9866b14465dcfaf12bcdfbc3392987bb559f37ac8b8a4c9b6359be7a3d7ea0

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography/tree/main/vectors
  summary: Test vectors for cryptography.
  description: |
    This package contains test vectors which are used in pyca/cryptography's tests.
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  dev_url: https://github.com/pyca/cryptography/tree/main/vectors
  doc_url: https://cryptography.io/

extra:
  recipe-maintainers:
    - jakirkham
