{% set name = "cryptography-vectors" %}
{% set version = "38.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptography_vectors-{{ version }}.tar.gz
  sha256: 0431fd107c1fbad0377704a7051945b3b391169fddc4f6fa0bd4edc6b6e235dd
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography
  license: BSD-3-Clause OR Apache-2.0
  license_family: BSD
  license_file:
    - LICENSE
    - LICENSE.BSD
    - LICENSE.APACHE
  summary: Test vectors for the cryptography package.
  dev_url: https://github.com/pyca/cryptography/tree/master/vectors
  doc_url: https://cryptography.io/en/{{ version }}/

extra:
  recipe-maintainers:
    - jakirkham
