{% set name = "cryptography-vectors" %}
{% set version = "41.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptography_vectors-{{ version }}.tar.gz
  sha256: 028dff94a8522ca818b11295ff12df55f348f33a193c0597ddfe8239e53d1582

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography
  license: BSD-3-Clause OR Apache-2.0
  license_url: https://github.com/pyca/cryptography/blob/{{ version }}/vectors/LICENSE
  license_family: BSD
  license_file:
    - LICENSE
    - LICENSE.BSD
    - LICENSE.APACHE
  description: |
    This package contains test vectors for the cryptography package.
  summary: Test vectors for the cryptography package.
  dev_url: https://github.com/pyca/cryptography/tree/{{ version }}/vectors
  doc_url: https://cryptography.io/en/{{ version }}/
  doc_source_url: https://github.com/pyca/cryptography/blob/{{ version }}/docs/index.rst

extra:
  recipe-maintainers:
    - jakirkham
