# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RiU5AnKe9LGvXzavqRpuh5UNccsQ5/TZofm7je5Om/XsPqHT3kyS1haTXPrnDi8UrUMAZV6Xu8fqkS64silFBVVBQCakq/JCdpemargPspUThcCIpHiN3QFJ5QojqSJOlQ8rc2rPMn3QHm4EZkaHALudwDr2U4HpvvqVK0HZlfB9R8z5XqR3YgaV7KZxFFbvgS5rdGgIxBzdh579W+Ey8ZN65PYRAbvW12JaOzppZpTsm2l1h3GnkYoVqtmSXTYhjiyQsAgy52NNI8MUJ+IzGrvrGyYbV6K6B7LE8i5tukzgn0xr5Eo7ETOMEhWuC3Z36ku2NLyovSmOQnXAKV7Bo26AwV5pSRgXEijBYThGyMFPqT+GU/7KZ4mpSUg9EW999/TJdQ6aY4W72TnNKHlyG9jRCTqzxZUrHt2PQbU6DbmrtZptwhji/WqAVJLbKtzwWF/bdcSH5PLWC/6blBnLnVT1TiRPog7G2mrxjThaUMSdTWPUXYE0naSMVr/CfovJmcJ0SVdvhfLCAFV1NFByFW+62t062mY0CUekg6a8TGK8pogUq0C+z8AHo41jS/WGKZbYWUTZzG0CGBlRsqYfzxSifKbvOQR5F2wm6yPGJf9xXfp2YYKkiMG7TE86HT+D8XbfE3kKBDx8CUCrhzHsmj7cSlmbW30By7Imm/DbjsY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
