travis:
  secure:
    BINSTAR_TOKEN: RiU5AnKe9LGvXzavqRpuh5UNccsQ5/TZofm7je5Om/XsPqHT3kyS1haTXPrnDi8UrUMAZV6Xu8fqkS64silFBVVBQCakq/JCdpemargPspUThcCIpHiN3QFJ5QojqSJOlQ8rc2rPMn3QHm4EZkaHALudwDr2U4HpvvqVK0HZlfB9R8z5XqR3YgaV7KZxFFbvgS5rdGgIxBzdh579W+Ey8ZN65PYRAbvW12JaOzppZpTsm2l1h3GnkYoVqtmSXTYhjiyQsAgy52NNI8MUJ+IzGrvrGyYbV6K6B7LE8i5tukzgn0xr5Eo7ETOMEhWuC3Z36ku2NLyovSmOQnXAKV7Bo26AwV5pSRgXEijBYThGyMFPqT+GU/7KZ4mpSUg9EW999/TJdQ6aY4W72TnNKHlyG9jRCTqzxZUrHt2PQbU6DbmrtZptwhji/WqAVJLbKtzwWF/bdcSH5PLWC/6blBnLnVT1TiRPog7G2mrxjThaUMSdTWPUXYE0naSMVr/CfovJmcJ0SVdvhfLCAFV1NFByFW+62t062mY0CUekg6a8TGK8pogUq0C+z8AHo41jS/WGKZbYWUTZzG0CGBlRsqYfzxSifKbvOQR5F2wm6yPGJf9xXfp2YYKkiMG7TE86HT+D8XbfE3kKBDx8CUCrhzHsmj7cSlmbW30By7Imm/DbjsY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
