travis:
  secure:
    BINSTAR_TOKEN: nRMdtxWo1UhYJePvW4lqjIGwI5OoJLbN5Sr6FcQRd9KglylDP1kbeeTbrfDNJo9QIi46Zf3sOzWbKub6diCWAFY05eVoqMrWmK1DTKdxLU+NQgH8WfVjf+LRNJzShPegbPHz8KnHX9JPWiNi2FwT36erF8VZ9COO+OQenkyaDvEgZOa8I3Q8nvwl6GQBtY2Rxc0V0H4Ts2cZaAAGu9Trhtn+rHcA6ArhEF66wQu2urGUMLg2j3CpgFDmgHQEfEOVg9hEzGQjGjFbezWoRI6XTUKsfxty0F5kf7Pwslz/QqRcw2dUP3XKsmm2S46XZJQft7ubIKJ/9ISi3tgRX+V6iXLjSN5x3Od0f58eyIzgahSnwjOSO0zIADHojA6HCRclwTfaH2svzQX159aehOjGOR4TP1i2IZjfbuiraQRKly6bOkjEfVJk+MFM0VFMPRP4gFu2Fb95w+coXqhY879w8frH2fv5M0GomPSuIjDotink0366gdrI+gwjCv2OIdM9XLjoRmxxo/T0LuAKuuYpnbFptSW0jyYBa/IAJkFhBXbPNj1b60iJtnBO96w/zBaPycFJpzD5WUvC0UjlYa9byFpPc6ZU8vka9Qe3Pcvw47aLeXrrecfE9NLXZjizzsPqOT/3T384NXRB0aW2F5YLsm5eiHY1P05MgJCwU2dwAu4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
